name: robocode-linux # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.9.5.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Robocode is a programming game where the goal is to code a robot battle tank
description: |
  Robocode is a programming game where the goal is to code a robot battle tank to compete against other robots in a battle
arena. So the name Robocode is short for "Robot code". The player is the programmer of the robot, who will have no
direct influence on the game. Instead, the player must write the AI of the robot telling it how to behave and react to
events occurring in the battle arena. Battles are running in real-time and on-screen.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  robocode_icon.png
title: Robocode

apps:
  robocode:
    command: robocode.sh
parts:
  robocode:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      robocode: build/
      robocode: man/man1/

architectures:
  - build-on: amd64

